name: Main Workflow 🚀

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1️⃣ Restore, Build & Test all in a matrix
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['9.0.x', '8.0.x']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      - name: Restore
        run: dotnet restore ./server.sln

      - name: Build
        run: dotnet build ./server.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./server.sln --no-build --verbosity normal

  # 2️⃣ Publish (only if tests passed on at least one matrix axis)
  publish:
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish
        run: dotnet publish ./server.sln --configuration Release --no-build

  
